-- Inserção dos dados
INSERT INTO Produtos (nome_produto, massa_total_gramas) VALUES
('Modulo Sensor de Temperatura', 18.0),
('Modulo Rele', 22.5),
('Termometro Digital com Display', 45.0),
('Carregador USB Portatil', 62.0),
('Controlador PWM para LED', 30.0),
('Fonte Regulada 5V', 58.0),
('Modulo de Potencia AC-DC', 120.0),
('Timer Programavel com Rele', 48.5),
('Central de Alarme PIR', 85.0),
('Modulo Bluetooth + Sensor LDR', 38.0),
('Placa Arduino Uno', 35.0),
('Placa Arduino Nano', 22.0),
('Placa de Desenvolvimento ESP32', 28.0),
('Modulo Sensor de Proximidade IR', 19.0),
('Controle Remoto infravermelho', 33.0),
('Medidor de Tensao Digital', 42.0),
('Dimmer Eletronico', 60.0),
('Fonte com Saida USB', 65.0),
('Modulo de Automacao Residencial', 77.0),
('Sensor de Gas MQ-2 com Placa', 36.0),
('Kit Display LCD com Sensor de Temp.', 58.5),
('Driver para Motor de Passo', 39.0),
('Modulo Fotovoltaico Mini', 48.0),
('Termostato Digital', 50.0),
('Modulo de Chaveamento de Carga', 55.0),
('Sensor de Luminosidade Automatico', 29.0),
('Placa de Expansao GPIO', 27.5),
('Modulo Receptor de RF 433MHz', 31.0),
('Placa Driver L298N', 46.0),
('Leitor RFID com Antena', 42.5),
('Sistema de Irrigacao Automatico', 93.0),
('Modulo USB de Programacao', 19.5),
('Kit com Motor e Encoder', 73.0),
('Disjuntor Eletronico Inteligente', 110.0),
('Sistema de Medicao de Corrente', 44.0),
('Interruptor Wi-Fi Inteligente', 88.0),
('Sistema de Monitoramento de Energia', 125.0),
('Placa Sensor de Chuva', 34.0),
('Detector de Fumaca Digital', 58.0),
('Fonte 12V com Protecao Termica', 132.0);
GO
