-- Inserção dos dados
INSERT INTO Processos (nome_processo, energia_sej_por_kg, descricao) VALUES
('Fundicao', 1.1E+09, 'Derretimento e moldagem de metais'),
('Refino de silicio', 2.3E+10, 'Purificacao termica do silicio'),
('Extrusao', 8.0E+08, 'Compressao de material em molde'),
('Soldagem', 5.0E+08, 'Uniao de metais por calor'),
('Usinagem', 6.2E+08, 'Corte e modelagem de pecas'),
('Injecao plastica', 7.5E+08, 'Molde de plastico sob pressao'),
('Montagem manual', 2.2E+08, 'Montagem feita por operador humano'),
('Montagem automatizada', 1.1E+09, 'Robos ou maquinas fazem a montagem'),
('Revestimento', 4.5E+08, 'Aplicacao de camadas protetoras'),
('Polimento', 3.6E+08, 'Suavizacao de superficies'),
('Recozimento', 1.4E+09, 'Aquecimento controlado para eliminar tensoes'),
('Impressao de PCB', 2.5E+09, 'Criacao da placa de circuito impresso'),
('Corte a laser', 9.8E+08, 'Corte de materiais com feixe de laser'),
('Sinterizacao', 1.6E+09, 'Compactacao de po sob calor'),
('Banho quimico', 1.9E+08, 'Processamento em solucao quimica'),
('Galvanoplastia', 2.3E+09, 'Revestimento metalico por eletrolise'),
('Anodizacao', 2.0E+09, 'Formacao de camada protetora por eletrolise'),
('Imersao em estanho', 1.1E+09, 'Protecao contra oxidacao'),
('Decapagem', 3.3E+08, 'Remocao quimica de impurezas'),
('Fotolitografia', 5.7E+09, 'Gravacao de circuitos em silicio'),
('Recozimento a vacuo', 1.8E+09, 'Tratamento termico sem oxigenio'),
('Colagem', 3.1E+08, 'Fixacao de pecas com adesivos'),
('Cura de resina', 4.7E+08, 'Endurecimento de resinas'),
('Desgaseificacao', 2.6E+08, 'Remocao de gases dissolvidos'),
('Aplicacao de pasta termica', 1.3E+08, 'Transferencia de calor entre pecas'),
('Pintura condutiva', 5.5E+08, 'Pintura que permite passagem de eletricidade'),
('Moldagem por compressao', 6.8E+08, 'Tecnica para materiais termoendureciveis'),
('Microfresagem', 4.0E+08, 'Fresagem de micropecas'),
('Refluicao', 3.2E+08, 'Fusao da solda para fixacao de componentes'),
('Passivacao', 3.6E+08, 'Protecao contra reacoes quimicas'),
('Tratamento termico', 1.2E+09, 'Aquecimento para alterar propriedades'),
('Metalizacao a vacuo', 2.0E+09, 'Revestimento metalico em ambiente sem ar'),
('Plasma de baixa pressao', 2.8E+09, 'Tratamento de superficies com plasma'),
('Deposicao quimica de vapor', 6.4E+09, 'Reacao de gases para formacao de camadas'),
('Reflow de solda', 4.1E+08, 'Aquecimento para derretimento controlado'),
('Fixacao por parafuso', 1.0E+08, 'Conexao de pecas com elementos roscados'),
('Encapsulamento de chips', 3.9E+08, 'Isolamento e protecao de semicondutores'),
('Limpeza ultrassonica', 2.9E+08, 'Remocao de residuos com ondas sonoras'),
('Corte CNC', 8.2E+08, 'Corte computadorizado de precisao'),
('Montagem SMT', 1.5E+09, 'Tecnologia de montagem de superficie');
GO
